// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeGetRoute, makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({})
};

import * as HomeRoute from "@/app/page.info";
import * as PokemonSearchAPIRoute from "@/app/api/pokemon/route.info";
import * as ApiPokemonPokemonIdRoute from "@/app/api/pokemon/[pokemonId]/route.info";
import * as PokemonDetailRoute from "@/app/pokemon/[pokemonId]/page.info";
import * as SearchRoute from "@/app/search/page.info";
import * as TanstackRoute from "@/app/tanstack/page.info";
import * as TestRoute from "@/app/test/page.info";

export const R = {
  Home: makeRoute("/", {
      ...defaultInfo,
      ...HomeRoute.Route
    }),
  PokemonDetail: makeRoute("/pokemon/[pokemonId]", {
      ...defaultInfo,
      ...PokemonDetailRoute.Route
    }),
  Search: makeRoute("/search", {
      ...defaultInfo,
      ...SearchRoute.Route
    }),
  Tanstack: makeRoute("/tanstack", {
      ...defaultInfo,
      ...TanstackRoute.Route
    }),
  Test: makeRoute("/test", {
      ...defaultInfo,
      ...TestRoute.Route
    }),

  api: {
    getPokemonSearchAPI: makeGetRoute(
      "/api/pokemon",
      {
        ...defaultInfo,
        ...PokemonSearchAPIRoute.Route
      },
      PokemonSearchAPIRoute.GET
    ),
    getApiPokemonPokemonId: makeGetRoute(
      "/api/pokemon/[pokemonId]",
      {
        ...defaultInfo,
        ...ApiPokemonPokemonIdRoute.Route
      },
      ApiPokemonPokemonIdRoute.GET
    ),
  },
} as const;