import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { H1 } from "@/components/ui/headings";
import TanstackProvider from "@/providers/tanstack-provider";
import { R } from "@/routes";
import Search from "./search/SearchList";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark px-2 md:px-5`}>
        <Navbar />
        <TanstackProvider>{children}</TanstackProvider>
      </body>
    </html>
  );
}

//
//
//
function Navbar() {
  return (
    <header className="flex mb-5 gap-2 text-2xl py-3 px-6 bg-blue-900 text-white rounded-b-xl shadow-gray-700 drop-shadow-2xl">
      {/* search/page.info.ts --> search in z object */}
      <R.Home.Link>Home</R.Home.Link>
      <R.Test.Link>Test</R.Test.Link>

      <R.Tanstack.Link>Tanstack</R.Tanstack.Link>
      {/* <Link href="/search" className="font-light"></Link> */}
      <R.Search.Link search={{ q: "bulb" }} className="font-light">
        Search
      </R.Search.Link>
    </header>
  );
}
